"""Produce the sized-solution certificates and the document that reports them.

Both outputs are generated. ``SIZED_SOLUTIONS.md`` used to be maintained by hand
and had drifted a full release behind the code - quoting verdicts, methods and
coverage figures the system no longer produced. A document that disagrees with
the artefact it describes is worse than no document, so it is written from the
certificates every time.
"""
from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from hydraulic_mas.sizing.coverage import coverage_summary
from hydraulic_mas.sizing.planner import size_problem

ROOT = pathlib.Path(__file__).resolve().parent

PREAMBLE = """\
# Sized and certified solutions — all seven problems

Generated by `reference/generate_report.py`. Do not edit by hand: every number
here is read off the certificate the verifier produced, so the two cannot drift.

Verification is **Phase-Resolved Quasi-Static**. Each phase is solved as an
algebraic system in the valve states the topology stage already proved, then
bounded over an operating envelope of ±2 points on each efficiency, and ±15 %
load where the brief states it. A verdict of PROVED means the guaranteed
enclosure lies inside the requirement *everywhere in that envelope*, not merely
at nominal; UNDECIDED means the enclosure straddles the bound; REFUTED means it
lies outside.

Every criterion is bounded the same way. Force, hold and pressure-ceiling checks
were nominal point evaluations until v0.7.0 and are now enclosures like the rest,
which is why some verdicts here differ from earlier releases.

Coverage is stated per problem, because a verdict is only as strong as the set of
statements it ranges over.
"""


def _fmt_cyl(sizing: dict) -> str:
    parts = [
        f"{name} {record['bore_mm']:g}/{record['rod_mm']:g}"
        for name, record in sizing.items()
        if isinstance(record, dict) and "bore_mm" in record
    ]
    return "<br>".join(parts)


def build(data: dict) -> tuple[dict, str]:
    out: dict = {}
    rows: list[str] = []
    for problem_id in sorted(data):
        entry = data[problem_id]
        result = size_problem(problem_id, entry["topology"], entry["requirements"])
        certificate = result.certificate
        out[problem_id] = {
            "sizing": {k: v for k, v in result.sizing.items() if v},
            "throttle_k": result.throttle_k,
            "certificate": certificate.to_dict(),
            "repairs": result.repairs,
            "notes": result.notes,
        }
        counts = certificate.counts()
        coverage = certificate.coverage()
        supply = result.sizing["__supply__"]
        rows.append(
            f"| {problem_id} | **{certificate.verdict}** | "
            f"{counts['PROVED']}P / {counts['UNDECIDED']}U / {counts['REFUTED']}R | "
            f"{coverage['answered']}/{coverage['stated']} | {_fmt_cyl(result.sizing)} | "
            f"{supply['displacement_cm3']:g} cm³/rev "
            f"({supply['displacement_cm3'] * supply['speed_rpm'] * 0.9 / 1000:.1f} L/min) | "
            f"{supply['relief_pa'] / 1e5:.1f} bar | {supply.get('motor_kw', 0):g} kW | "
            f"{supply.get('reservoir_l', 0):g} L | {supply.get('valve_size', '')} |"
        )

    lines = [PREAMBLE, "",
             "| Problem | Verdict | Criteria | Answered | Actuators | Pump | Relief | Motor | Tank | Valves |",
             "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    lines.extend(rows)
    lines.append("")

    for problem_id in sorted(data):
        record = out[problem_id]
        certificate = record["certificate"]
        sizing = record["sizing"]
        supply = sizing["__supply__"]
        lines += ["---", "", f"## {problem_id} — {certificate['verdict']}", "",
                  "**Selected components**", "",
                  "| Item | Selection | Basis |", "| --- | --- | --- |"]
        for name, item in sizing.items():
            if isinstance(item, dict) and "bore_mm" in item:
                lines.append(
                    f"| {name} | {item['bore_mm']:g}/{item['rod_mm']:g} mm | "
                    f"cap {item['cap_area_m2'] * 1e6:.0f} mm², annulus "
                    f"{item['annulus_area_m2'] * 1e6:.0f} mm², ratio "
                    f"{item['cap_area_m2'] / item['annulus_area_m2']:.2f} |")
        lines += [
            f"| Pump | {supply['displacement_cm3']:g} cm³/rev at {supply['speed_rpm']:g} rpm | "
            f"{supply['displacement_cm3'] * supply['speed_rpm'] * 0.9 / 1000:.2f} L/min at η_v 0.90 |",
            f"| Relief valve | {supply['relief_pa'] / 1e5:.1f} bar | chosen by search over the "
            "settings the verifier scores |",
            f"| Prime mover | {supply.get('motor_kw', 0):g} kW | shaft power at the worst phase, η_o 0.85 |",
            f"| Reservoir | {supply.get('reservoir_l', 0):g} L | three times delivered flow |",
            f"| Directional valves | {supply.get('valve_size', '')} | ≥125 % of "
            f"{supply.get('peak_return_lpm', 0):.1f} L/min peak return |",
        ]
        for label in ("suction", "pressure", "return"):
            if supply.get(f"{label}_tube"):
                lines.append(f"| {label.title()} line | {supply[f'{label}_tube']} | "
                             "standard tube at the usual velocity for this duty |")
        lines += ["", "**Operating points**", "",
                  "| Phase | Regime | Velocity | Pump | Supply | Exhaust | Over relief |",
                  "| --- | --- | --- | --- | --- | --- | --- |"]
        for phase_id, point in certificate["operating_points"].items():
            lines.append(
                f"| {phase_id} | {point['regime']} | {point['velocity_m_min']:.3f} m/min | "
                f"{point['pump_pressure_bar']:.2f} bar | {point['supply_pressure_bar']:.2f} bar | "
                f"{point['exhaust_pressure_bar']:.2f} bar | {point['relief_flow_lpm']:.2f} L/min |")
        lines += ["", "**Certificates**", "",
                  "| Criterion | Required | Achieved (enclosure) | Verdict | Method |",
                  "| --- | --- | --- | --- | --- |"]
        for item in certificate["criteria"]:
            lines.append(
                f"| {item['criterion_id']} | {item['required']} | {item['achieved']} | "
                f"{item['verdict']} | {item['method']} |")

        coverage = certificate["coverage"]
        summary = coverage_summary(certificate["uncovered"])
        lines += ["", "**Coverage**", "",
                  f"{coverage['answered']} of {coverage['stated']} stated acceptance criteria are "
                  f"answered by {coverage['checks']} checks. The rest:", ""]
        if summary:
            for reason, count in sorted(summary.items(), key=lambda pair: -pair[1]):
                names = ", ".join(
                    f"`{item['metric']}`" for item in certificate["uncovered"]
                    if item["reason"] == reason)
                lines.append(f"- **{count}** {reason} — {names}")
        else:
            lines.append("- none; every stated criterion is answered")

        if certificate["findings"]:
            lines += ["", "**Findings**", ""]
            for finding in certificate["findings"]:
                lines.append(f"- `[{finding['layer']}] {finding['code']}` — {finding['message']}")
        if record["notes"]:
            lines += ["", "**Planner notes**", ""]
            lines.extend(f"- {note}" for note in record["notes"])
        lines.append("")
    return out, "\n".join(lines)


def main() -> None:
    data = json.loads((ROOT / "validated_topologies.json").read_text())
    out, document = build(data)
    (ROOT / "sized_certificates.json").write_text(json.dumps(out, indent=1, default=str))
    (ROOT / "SIZED_SOLUTIONS.md").write_text(document, encoding="utf-8")
    print("wrote", ROOT / "sized_certificates.json")
    print("wrote", ROOT / "SIZED_SOLUTIONS.md")
    for problem_id, value in out.items():
        certificate = value["certificate"]
        print(problem_id, certificate["verdict"], certificate["counts"],
              "coverage", certificate["coverage"])


if __name__ == "__main__":
    main()
